2012/05/12 18:55:28 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'yii_test'@'localhost' (using password: YES)' in /http/yii-1.1.10.r3566/framework/db/CDbConnection.php:382
Stack trace:
#0 /http/yii-1.1.10.r3566/framework/db/CDbConnection.php(331): CDbConnection->open()
#1 /http/yii-1.1.10.r3566/framework/db/CDbConnection.php(309): CDbConnection->setActive(true)
#2 /http/yii-1.1.10.r3566/framework/base/CModule.php(388): CDbConnection->init()
#3 /http/yii-1.1.10.r3566/framework/base/CModule.php(104): CModule->getComponent('db')
#4 /http/yii-1.1.10.r3566/framework/gii/generators/model/ModelCode.php(54): CModule->__get('db')
#5 /http/yii-1.1.10.r3566/framework/web/CFormModel.php(40): ModelCode->init()
#6 /http/yii-1.1.10.r3566/framework/gii/CCodeGenerator.php(152): CFormModel->__construct()
#7 /http/yii-1.1.10.r3566/framework/gii/CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 /http/yii-1.1.10.r3566/framework/web/actions/CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 /http/yii-1.1.10.r3566/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /http/yii-1.1.10.r3566/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /http/yii-1.1.10.r3566/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(276): CController->run('')
#13 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(135): CWebApplication->runController('gii/model')
#14 /http/yii-1.1.10.r3566/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /http/testdrive/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/david/testdrive/index.php?r=gii/model
HTTP_REFERER=http://localhost/david/testdrive/index.php?r=gii/default/index
---
2012/05/12 18:55:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'yii_test'@'localhost' (using password: YES)' in /http/yii-1.1.10.r3566/framework/db/CDbConnection.php:382
Stack trace:
#0 /http/yii-1.1.10.r3566/framework/db/CDbConnection.php(331): CDbConnection->open()
#1 /http/yii-1.1.10.r3566/framework/db/CDbConnection.php(309): CDbConnection->setActive(true)
#2 /http/yii-1.1.10.r3566/framework/base/CModule.php(388): CDbConnection->init()
#3 /http/yii-1.1.10.r3566/framework/base/CModule.php(104): CModule->getComponent('db')
#4 /http/yii-1.1.10.r3566/framework/gii/generators/model/ModelCode.php(54): CModule->__get('db')
#5 /http/yii-1.1.10.r3566/framework/web/CFormModel.php(40): ModelCode->init()
#6 /http/yii-1.1.10.r3566/framework/gii/CCodeGenerator.php(152): CFormModel->__construct()
#7 /http/yii-1.1.10.r3566/framework/gii/CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 /http/yii-1.1.10.r3566/framework/web/actions/CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 /http/yii-1.1.10.r3566/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /http/yii-1.1.10.r3566/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /http/yii-1.1.10.r3566/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(276): CController->run('')
#13 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(135): CWebApplication->runController('gii/model')
#14 /http/yii-1.1.10.r3566/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /http/testdrive/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/david/testdrive/index.php?r=gii/model
HTTP_REFERER=http://localhost/david/testdrive/index.php?r=gii/default/index
---
2012/05/12 18:56:02 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1045] Access denied for user 'yiitest'@'localhost' (using password: YES)' in /http/yii-1.1.10.r3566/framework/db/CDbConnection.php:382
Stack trace:
#0 /http/yii-1.1.10.r3566/framework/db/CDbConnection.php(331): CDbConnection->open()
#1 /http/yii-1.1.10.r3566/framework/db/CDbConnection.php(309): CDbConnection->setActive(true)
#2 /http/yii-1.1.10.r3566/framework/base/CModule.php(388): CDbConnection->init()
#3 /http/yii-1.1.10.r3566/framework/base/CModule.php(104): CModule->getComponent('db')
#4 /http/yii-1.1.10.r3566/framework/gii/generators/model/ModelCode.php(54): CModule->__get('db')
#5 /http/yii-1.1.10.r3566/framework/web/CFormModel.php(40): ModelCode->init()
#6 /http/yii-1.1.10.r3566/framework/gii/CCodeGenerator.php(152): CFormModel->__construct()
#7 /http/yii-1.1.10.r3566/framework/gii/CCodeGenerator.php(64): CCodeGenerator->prepare()
#8 /http/yii-1.1.10.r3566/framework/web/actions/CInlineAction.php(50): CCodeGenerator->actionIndex()
#9 /http/yii-1.1.10.r3566/framework/web/CController.php(309): CInlineAction->runWithParams(Array)
#10 /http/yii-1.1.10.r3566/framework/web/CController.php(287): CController->runAction(Object(CInlineAction))
#11 /http/yii-1.1.10.r3566/framework/web/CController.php(266): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(276): CController->run('')
#13 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(135): CWebApplication->runController('gii/model')
#14 /http/yii-1.1.10.r3566/framework/base/CApplication.php(162): CWebApplication->processRequest()
#15 /http/testdrive/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/david/testdrive/index.php?r=gii/model
HTTP_REFERER=http://localhost/david/testdrive/index.php?r=gii/default/index
---
2012/05/13 01:09:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user".' in /http/yii-1.1.10.r3566/framework/web/CWebApplication.php:280
Stack trace:
#0 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(135): CWebApplication->runController('user')
#1 /http/yii-1.1.10.r3566/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /http/testdrive/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/david/testdrive/index.php?r=user
---
2012/05/17 17:49:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in /http/yii-1.1.10.r3566/framework/web/CWebApplication.php:280
Stack trace:
#0 /http/yii-1.1.10.r3566/framework/web/CWebApplication.php(135): CWebApplication->runController('index')
#1 /http/yii-1.1.10.r3566/framework/base/CApplication.php(162): CWebApplication->processRequest()
#2 /http/testdrive/index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/david/testdrive/index.php?r=index
---
